### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/magicdawn#151]

**Comment by magicdawn** [comment]
## 常用

```yml
# name: Node.js CI

on:
  - push
  - pull_request

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with: { version: 7 }

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm test-cover
      - uses: codecov/codecov-action@v3
```

### `pnpm/action-setup`


- 这个仓库内置了一个很大的 `pnpm.js`, 用于 `pnpm add pnpm@指定版本`
- 默认 dest = `~/setup-pnpm`
- 导出 `PNPM_HOME` = `~/setup-pnpm/node_modules/.bin/`, store path 位于 `PNPM_HOME/store/v3`
- 不提供 cache 功能, README 引导使用 `actions/cache`

### `actions/setup-node`

- 提供 cache 功能, `cache: pnpm` 会自动 cache `pnpm store path` 目录, 与 `pnpm/action-setup` 建议的一样.
- 会换成 cache path, 而不是 node_modules
