### ISSUE TITLE
字体

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/magicdawn#16]
字体什么的

highlight

``` css
pre,code {
    white-space: pre;
    display: inline-block;
    margin: 0;
    font: 14px/1.8em Menlo, Consolas, "Courier New", Courier, "Liberation Mono", monospace;
    padding: 0 0.5em
}
```

jekyllrb.com 主站,字体 

``` css
font: 300 21px Lato, 'Helvetica Neue', Helvetica, Arial, sans-serif;
/* font-weight : 300*/
```

**Comment by magicdawn** [comment]
less

@import "xxx.css" 跟 @import (css)"xxx.css" 一样,由ext推断出
import css 会保留原样.........坑...

@import (inline) 就是导入文本,但不处理

@import (less) 导入less

**Comment by magicdawn** [comment]
gulp-less 这个插件 有问题不报错... 找了半天...

**Comment by magicdawn** [comment]
## meituan font

### main site
```css
  font: 400 14px/1.5 "Hiragino Sans GB","WenQuanYi Micro Hei",tahoma,sans-serif;
```
win7 x64 chrome v42 , 实际render字体为 `SimSun`

### mos
主要是这个,重复写的...不用inherit 差评...
```css
font-family: "Microsoft Yahei","Hiragino Sans GB","Helvetica Neue",Arial,sans-serif;
```

**Comment by magicdawn** [comment]
http://jobs.ele.me

```css
font-family: 'Helvetica Neue', 'Microsoft Yahei', 'Hiragino Sans GB', 'Microsoft Sans Serif', 'WenQuanYi Micro Hei', sans-serif;
```

**Comment by magicdawn** [comment]
## rem

单位 rem , 是相对 root element的font-size值的
```css
html{
  font-size: 10px;
}

p{
  margin-top: 1.5rem; // 1.5 * 10 = 15px
}
```
