### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/magicdawn#184]

**Comment by magicdawn** [comment]
https://mp.weixin.qq.com/s/smm6AE9xDUxzL5fVkGsINg

> 这里有几个关键词，即“亚克力（Acrylic Material）”、“磨砂玻璃（Frosted Glass）”、“Neumorphism”和“Glassmorphism”。但它们的出现在我们的世界中是“磨砂玻璃（Frosted Glass）”，“亚克力（Acrylic Material）”，“Neumorphism”，然后才是“Glassmorphism”。

## 磨砂玻璃

```css
.card,
.card__media,
.card__content {
  background-color: rgba(255, 255, 255, 0.05);
  backdrop-filter: blur(10px);
}
```

可以看到 
- background-color 接近透明, alpha 非常小
- backdrop-filter 一个 blur 
透明+磨砂
