### ISSUE TITLE
hexo@3

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/magicdawn#21]
hexo3 用Promise重写,问题还真多...

**Comment by magicdawn** [comment]
# hexo-cli

库
- [tildify](https://github.com/sindresorhus/tildify) 将绝对路径转化为 ~/xxx
- hexo-fs 封装的一堆fs方法为 Promise

cli 完成的也就是 基本的功能,如 打印help信息,打印版本,加载插件,基本的Logger...

结束问候语 hexo-cli/lib/goodbye.js 哈哈- :)

**Comment by magicdawn** [comment]
我的hexo g还是一堆错....

怎么回事..................................................

**Comment by magicdawn** [comment]
# hexo highlight

1. `_config.yml` 
```
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
```
