### ISSUE TITLE
jshint

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/magicdawn#28]
# jshint

## 常见配置

**Comment by magicdawn** [comment]
## 我的配置

TODO: add my `.jshintrc` file

**Comment by magicdawn** [comment]
## 常见配置
参考 https://github.com/jshint/jshint/blob/master/examples/.jshintrc

- new Constructor , 不带括号, supernew = true
- obj.prop v.s obj['prop'] , sub = true , 可以使用方括号的形式

**Comment by magicdawn** [comment]
## warning 部分

不可在.jshintrc 中配置,使用注释 supress warning message

- return a = b; 这个在返回的时候赋值。`/*jshint -W093 */`

**Comment by magicdawn** [comment]
# jsbeautify

```json
{
  "indent_size": 2,
  "indent_char": " ",
  "eol": "\n",
  "indent_level": 0,
  "indent_with_tabs": false,
  "preserve_newlines": true,
  "max_preserve_newlines": 3,
  "jslint_happy": false,
  "space_after_anon_function": false,
  "brace_style": "collapse",
  "keep_array_indentation": false,
  "keep_function_indentation": false,
  "space_before_conditional": true,
  "break_chained_methods": false,
  "eval_code": false,
  "unescape_strings": false,
  "wrap_line_length": 0,
  "wrap_attributes": "auto",
  "wrap_attributes_indent_size": 2,
  "end_with_newline": false
}
```

**Comment by magicdawn** [comment]
# travis ci

.travis.yml

```yml
language: node_js
node_js:
  - "iojs-v1"
  - "iojs-v2"
script: "make test-cover"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
notifications:
  email: false
```

其中的 node_js 版本填的是可以用 nvm 安装的
